name: dysscreen_app_v1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # state management, intelligent dependency injection, and route management
  get: ^4.1.4

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.1
  share_plus: ^6.3.4
  url_launcher: ^6.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/